### ISSUE TITLE
Building SOFA on AUMC

### ISSUE THREAD

**Issue by dplecko** [AmsterdamUMC/AmsterdamUMCdb#11]
Hi,

We are trying to include the `aumc` dataset in our `ricu` R-package which currently loads the MIMIC, eICU and HiRID data simultaneously. To this end, we are also trying to construct SOFA scores at continuous time points on the dataset. 

There are several questions that came up and I think it would be great if you could help us out with:

- What would be the best way of determining whether a patient is mechanically ventilated (the fact that things are in dutch makes figuring this out a bit complicated)
- I found various different item IDs which do not appear in the `drugitems` table. For instance, norepinephrine has ID 8676, but the following query
```
> subset(aumc$drugitems, itemid == 8676)
Empty data.table (0 rows and 31 cols): admissionid,orderid,ordercategoryid,ordercategory,itemid,item...
```
shows there is apparently no norepinephrine data in the table. The `drugitems` table for me has 4 907 269 rows... is it possible that this is not the complete table?

- Are the Glasgow Coma Scale (GCS) scores available in the dataset? Also, what do you think would be the best way of determining whether a patient is sedated?

Thank you in advance.

Best,
Drago

**Comment by patrickthoral** [comment]
For SOFA scores (and many other interesting chacteristics), please check the Table 1 notebook in the papers folder: [paper-table1-patient-data-characteristics.ipynb](https://github.com/AmsterdamUMC/AmsterdamUMCdb/blob/master/paper/paper-table1-patient-data-characteristics.ipynb). This will also show information on how to determine whether a patient has been ventilated (sql_mechanical_ventilation)

I am not sure from which table you got  itemid 8676 from. Noradrenalin has itemid 7229.

GCS is available as the components (eyes, motor, verbal). Please check the same notebook (sql_gcs). For sedation you should the use of 'Injecties CZS/Sedatie/Analgetica' and '2. Spuitpompen' with sedatives (e.g. propofol, midazolam).
