### ISSUE TITLE
Units of measurement

### ISSUE THREAD

**Issue by dplecko** [AmsterdamUMC/AmsterdamUMCdb#12]
Hi,

I have a couple of questions about various units of measurement in the dataset. I am trying to convert the units so they match the units used in MIMIC/eICU. I have the following questions:

- base excess (itemids 6807 and 9994)
![Screen Shot 2020-08-10 at 13 16 56](https://user-images.githubusercontent.com/43063243/89777424-f339dc00-db0b-11ea-93c7-44aa86801ee2.png)
It seems like the distribution is asymmetric, and different from the other 3 large databases. Any thoughts as to why this might be?
- insulin (itemids 2663 / 4218 / 6929 (_not all of these actually appear in the data_))
![Screen Shot 2020-08-10 at 13 17 12](https://user-images.githubusercontent.com/43063243/89777507-241a1100-db0c-11ea-8244-354a947d2f98.png)
The standard unit for insulin is in units... and it seems the unit used in AUMC is miligrams. Any thoughts on how to best convert from mg to units?
- basophils (itemid 14256) and lymphocytes (itemid 14258)
![Screen Shot 2020-08-10 at 13 21 37](https://user-images.githubusercontent.com/43063243/89777688-722f1480-db0c-11ea-8974-e44d15446cfb.png)
So the target unit used in most datasets is in fact % (or proportion). The unit used in AUMC is "10^9/L". Is there any hope of converting between the two? Or do you think that I would need _all cells counts at the same time_ to convert between these two ways of measurement?

Thank you in advance!

Best,
Drago

**Comment by patrickthoral** [comment]
Hello Drago,

Sorry, I did not notice your issue. 

- Base excess
With respect to the base excess values. Please check the `tag` associated with each value. In this specific case, there's a `-` tag, so the following code should create the actual values:

```python
df.loc[(df['tag'] == '-'), 'corrected_value'] = - df['value']
df.loc[~(df['tag'] == '-'), 'corrected_value'] = df['value']
```

![image](https://user-images.githubusercontent.com/42101283/92930509-75d2f580-f442-11ea-8500-72bc7c5e76e4.png)

- insulin:
we actually do use IU (international units) for insulin dosing, but I'll have a look

- Proportion
As the name suggests, it's the proportion/percentage of the total white blood cells, so just divide by that.

**Comment by patrickthoral** [comment]
@dplecko 

I checked the insulin itemids and these are not the correct ones. Could you please tell me were you got these itemids from. A simple working solution would be:
```sql
SELECT * FROM drugitems
WHERE item ILIKE '%insulin%'
```

Please note that some items have a `rate`, meaning an amount of international units (IU, Dutch: IE) per unit of time (most often hours).

**Comment by patrickthoral** [comment]
For your reference, these are the insulins I would use:

```python
sql_insulin = """
SELECT * FROM drugitems
WHERE item ILIKE '%insulin%'
"""
insulin = pd.read_sql(sql_insulin,con)
insulin[['item','itemid','ordercategoryid','ordercategory']].drop_duplicates()
```

  | item | itemid | ordercategoryid | ordercategory
-- | -- | -- | -- | --
0 | Actrapid (Insuline) | 7624 | 65 | 2. Spuitpompen
10 | Insuline aspart (Novorapid) | 19129 | 65 | 2. Spuitpompen
13 | Velosuline (Insuline) | 9014 | 65 | 2. Spuitpompen
23 | Insuline aspart (Novorapid) | 19129 | 67 | Injecties Hormonen/Vitaminen/Mineralen
150 | Velosuline (Insuline) | 9014 | 67 | Injecties Hormonen/Vitaminen/Mineralen
790 | Actrapid (Insuline) | 7624 | 67 | Injecties Hormonen/Vitaminen/Mineralen
1616 | Actrapid (Insuline) | 7624 | 55 | Infuus - Crystalloid
2153 | Velosuline (Insuline) | 9014 | 55 | Infuus - Crystalloid
2563 | Insuline aspart (Novorapid) | 19129 | 55 | Infuus - Crystalloid
4883 | Insulatard (Insuline) | 10755 | 67 | Injecties Hormonen/Vitaminen/Mineralen
11595 | Mixtard (Insuline) 30-70 | 9095 | 67 | Injecties Hormonen/Vitaminen/Mineralen
15664 | Novomix (insuline) | 10599 | 67 | Injecties Hormonen/Vitaminen/Mineralen
17977 | LANTUS (insuline glargine) | 19885 | 67 | Injecties Hormonen/Vitaminen/Mineralen
133932 | Velosuline (Insuline) | 9014 | 21 | Niet iv Antimicrobiele middelen

Note the `Spuitpompen` and `Infuus` document a rate.

**Comment by dplecko** [comment]
Perfect, thanks!
