### ISSUE TITLE
ICD codes

### ISSUE THREAD

**Issue by nbenn** [AmsterdamUMC/AmsterdamUMCdb#14]
Does AmsterdamUMCdb contain diagnostic ICD codes (preferably ICD-9, as this is what MIMIC contains)? I could not find anything, but this may be down to my Dutch language skills. I could find some "ICD" items in processitems, but I assume this has nothing to do with ICD as in "International Classification of Diseases", right?

**Comment by patrickthoral** [comment]
No, ICD would be 'implantable cardioverter-defibrillator (ICD)', in this case. I just updated the repository with a concepts folder containing reasons for admission: Please check it [here](https://github.com/AmsterdamUMC/AmsterdamUMCdb/tree/master/concepts/diagnosis). It contains the reasons for ICU admission (primary diagnosis) using different classification systems, mainly APACHE based. It doesn't contain International Classification of Diseases currently, though.

**Comment by nbenn** [comment]
@patrickthoral Thanks for clarifying and for sharing the script on admission diagnoses. If in your patient management system ICD codes are available and it was feasible to export to `AmsterdamUMCdb`, this could be a useful addition. In R there is a nice [package for working with ICD codes](https://github.com/jackwasey/icd) and we have been looking into using this on MIMIC and eICU for convenient calculation of comorbidities and medical risk scores. Also it could be of use to all us non-Dutch speakers. I will go ahead and close for now, as my question whether this currently is available has been answered. Thanks again!
