### ISSUE TITLE
fewer eosinophils than basophils?

### ISSUE THREAD

**Issue by dplecko** [AmsterdamUMC/AmsterdamUMCdb#18]
Hi,

I find that there are many more basophil than eosinophil measurements - which is perhaps unsual since they usually come together?

![eos](https://user-images.githubusercontent.com/43063243/99664443-77cfbb00-2a68-11eb-844f-7586988aa493.png)

Thanks,
Drago

**Comment by patrickthoral** [comment]
@dplecko 
Took a bit longer than expected, but probably missing one id:

```SQL
SELECT itemid, item, COUNT(*) FROM numericitems
WHERE itemid in (
    6772 --Eos Abs Tel None
    ,6773 --Eosinofielen None
    ,9967 --Eo app (bloed) 10^9/l
    ,11790 --Eo % (bloed) Geen
    ,14334 --EOabs (bloed 10^9/l
    )
GROUP BY itemid, item
```

 itemid | item | count
| -- | -- | --
6772 | Eos Abs Tel | 3
6773 | Eosinofielen | 44
9967 | Eo app (bloed) | 10277
11790 | Eo % (bloed) | 4633
14334 | EOabs (bloed) | 2797



| itemid | item | count
| -- | -- | --
6768 | Basofielen | 36
11710 | Baso % (bloed) | 3937
14256 | Baso (bloed) | 11618

**Comment by dplecko** [comment]
Thanks, very helpful.
