### ISSUE TITLE
Information on AUMC ICUs

### ISSUE THREAD

**Issue by nbenn** [AmsterdamUMC/AmsterdamUMCdb#19]
I was trying to figure out some stats on the hospital where this dataset originates from. What I gathered so far:

- in 2018, Amsterdam UMC resulted from a merger of VU Medical Center (VUmc) and Academic Medical Center (AMC). Data was collected 2003 through 2016; I assume from VUmc, is this correct?
- Adult Intensive Care at VUmc is organized into 3 units: two intensive care units with 22 beds and a 12 bed Medium Care or High Dependency unit, while VUmc as a whole is a 733 bed hospital
- From the 2018 HSMR report, I gather that there are roughly 20,000 yearly admissions to VUmc. I could not find a number on yearly admissions to ICUs. What would be a ballpark estimate?

@patrickthoral Are my numbers ok? Happy to hear from you in case I got something wrong.

**Comment by patrickthoral** [comment]
@nbenn 
> in 2018, Amsterdam UMC resulted from a merger of VU Medical Center (VUmc) and Academic Medical Center (AMC). Data was collected 2003 through 2016; I assume from VUmc, is this correct?

Though the project originated from intensivists from VUmc, including myself, we try not to emphasize the distinction between both locations in publications. It's legally not a merger though, but only a merger of the executive board. 

> Adult Intensive Care at VUmc is organized into 3 units: two intensive care units with 22 beds and a 12 bed Medium Care or High Dependency unit, while VUmc as a whole is a 733 bed hospital

We would normally use 'up to 32 bed ICU and 12 bed high dependency unit'
>From the 2018 HSMR report, I gather that there are roughly 20,000 yearly admissions to VUmc. I could not find a number on yearly admissions to ICUs. What would be a ballpark estimate?

You could probably just divide the number of admissions (23,106) in the database by ~13 years but this is from the original database:
| year	| admissions per year
--|--
2003	|  713
2004|	1450
2005|	1368
2006|	1461
2007|	1386
2008|	1475
2009|	1909
2010|	2092
2011|	1971
2012|	2369
2013|	2539
2014|	2558
2015|	1925
2016|	339

**Comment by paulelbers** [comment]
Waarom eigenlijk zo weinig in 2016?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by nbenn** [comment]
@patrickthoral Thanks for getting back to me. I'll go ahead and close.
