### ISSUE TITLE
Where to find culture information for sepsis-3 cohort

### ISSUE THREAD

**Issue by yinchangchang** [AmsterdamUMC/AmsterdamUMCdb#20]
Hi,
We are searching cohort based on sepsis-3 which involves the concept of “suspected infection” – i.e., either patients those had body fluids sampled for culture and received antibiotics. Does AmsterdamUMCdb contains any culture information? I cannot find any by searching “culture” on all tables. Is there any synonym for culture at AmsterdamUMCdb?

**Comment by patrickthoral** [comment]
You should probaby have a look at: https://github.com/AmsterdamUMC/AmsterdamUMCdb/blob/master/concepts/diagnosis/reason_for_admission.ipynb.

It contains working definition for sepsis, including one based on 'suspected infection' based on samples drawn for culture. These are the id's you are probably after:
```sql
FROM procedureorderitems
    WHERE 
        itemid IN (
        --8097, --Sputumkweek afnemen -> often used routinely
        --8418, --Urinekweek afnemen
        --8588, --MRSA kweken afnemen 
        9189, --Bloedkweken afnemen
        9190, --Cathetertipkweek afnemen
        --9191, --Drainvochtkweek afnemen
        --9192, --Faeceskweek afnemen -> Clostridium
        --9193, --X-Kweek nader te bepalen
        --9194, --Liquorkweek afnemen
        --9195, --Neuskweek afnemen
        --9197, --Perineumkweek afnemen -> often used routinely
        --9198, --Rectumkweek afnemen -> often used routinely
        9200, --Wondkweek afnemen
        9202, --Ascitesvochtkweek afnemen
        --9203, --Keelkweek afnemen -> often used routinely
        --9204, --SDD-kweken afnemen -> often used routinely
        9205 --Legionella sneltest (urine)
        --1302, --SDD Inventarisatiekweken afnemen -> often used routinely
        --19663, --Research Neuskweek COUrSe
        --19664, --Research Sputumkweek COUrSe
        )
```

**Comment by yinchangchang** [comment]
It helps a lot. Thanks very much!
