### ISSUE TITLE
Diabetes diagnosis

### ISSUE THREAD

**Issue by dplecko** [AmsterdamUMC/AmsterdamUMCdb#22]
Hi,

I was wondering if it was possible to reliably determine whether patients are diabetic or not?

Thanks!

**Comment by patrickthoral** [comment]
If 'reliably' means based on diagnostic codes, then 'no'. But there are other possibilities of course, e.g. based on use of anti-diabetic agents (https://www.whocc.no/atc_ddd_index/?code=A10&showdescription=yes)  or on documented glucose values (https://en.wikipedia.org/wiki/Diabetes#Diagnosis), e.g. any glucose > 11.1 mmol/l
