### ISSUE TITLE
ventilatory mode

### ISSUE THREAD

**Issue by snafees** [AmsterdamUMC/AmsterdamUMCdb#23]
Do you have more information in the dataset under `listitems` that gives data on parameters besides ventilatory mode? E.g., ventilator settings, blood/gas parameters, anesthesia? And permission to access this data requires one to follow instructions [here](https://amsterdammedicaldatascience.nl/#amsterdamumcdb), correct? Thanks for your help!

**Comment by patrickthoral** [comment]
`listitems` only contains categorical data. 
You are probably looking for numerical values from `numericitems` (some examples only):
Ventilator settings: (PEEP, respiratory rate [Dutch: Adem frequentie)], PC above PEEP, tidal volume) 
Blood gases: pH, pCO2, pO2.
I am not sure what you mean by anesthesia? All medication including sedatives, anesthestics and analgesics are `drugitems`

You are correct that access to the data requires following those instructions. Importantly, it specifically requires the signature of an intensivist  from your institution or an affiliated institution.
