### ISSUE TITLE
How should I inquire about patients admitted to the hospital for trauma?

### ISSUE THREAD

**Issue by xujiameng** [AmsterdamUMC/AmsterdamUMCdb#24]
I searched the content about "traum" in the reason view, but only 1216 people were filtered out. Considering that the UMC database contains so many patients, I suspect that my query is not complete (MIMICIII database contains 3112 patients who were admitted to hospital due to trauma, and the EICU database contains 12009 people. The data volume of these databases is similar to that of UMC, but the trauma patients are much higher than that of UMC database).

     Apart from searching the reason view, can I search for patients admitted to hospital due to trauma in other ways?

**Comment by xujiameng** [comment]
sorry，reason view means “reason_for_admission”

**Comment by patrickthoral** [comment]
MIMIC III contains ~ 60k patients. You found ~3000 are trauma. AmsterdamUMC contains 1243 trauma patients of 23k admissions
[reason_for_admission] (https://github.com/AmsterdamUMC/AmsterdamUMCdb/blob/master/concepts/diagnosis/reason_for_admission.ipynb), so similarly both data sets contain about 5% trauma patients. I think this is expected. You might verify this with the admissions table:
`Specialty = 'Traumatologie'`, but that will not contain the isolated traumatic brain injury patients.
