### ISSUE TITLE
Ethnicity of patients 

### ISSUE THREAD

**Issue by FrancescaAlf** [AmsterdamUMC/AmsterdamUMCdb#26]
Hi, 
Does AmsterdamUMC DB contain any information about ethnicity? Or is there a way to derive it? Thanks

**Comment by patrickthoral** [comment]
Hello Francesa,

Unfortunately, Dutch law only allows documentation of 'ethnicity' in very specific situations for well-defined goals. This means that is not available in the AmsterdamUMCdb dataset. For some patients there is some additional information (e.g. language), but that is not very reliably documented.
