### ISSUE TITLE
High Resolution Waveforms

### ISSUE THREAD

**Issue by etolma5** [AmsterdamUMC/AmsterdamUMCdb#29]
Hello,

According to ST Vistesen et al letter in _BJA_ (forthcoming, on VitalDB database in Korea), the AmsterdamUMCdb has vital sign sample resolution of once per minute. I'm looking for high resolution waveform databases at academic medical centres and have found 7 in US, 1 in Canada, and none in Europe. In United States I've seen: U Michigan, U Virginia, UCLA/UCI, Case Western Reserve U, Johns Hopkins U, U Maryland, MIT (MIMIC at BIDMC). In Canada, 'Artemis' system at Toronto Children's, built by U Toronto.

My questions are: 1) Does AmsterdamUMCdb have high-resolution (125 hz sample rate or higher) ECG and/or invasive BP waveforms? and 2) Are you aware of any other academic medical centres doing high temporal resolution waveform capture and curation?

Thanks

Ebenezer Tolman
_Anesthesia Technician Supervisor
Tufts Medical Center
Boston MA USA_

**Comment by paulelbers** [comment]
Currently, AmsterdamUMCdb does not contain waveform data.
