### ISSUE TITLE
Typo in calculation of liver SOFA score

### ISSUE THREAD

**Issue by mattwillis47** [AmsterdamUMC/AmsterdamUMCdb#36]
Hi guys,
I noticed while looking through the calculation of liver SOFA scores in [AmsterdamUMCdb/concepts/severityscores/sofa.ipynb ](https://github.com/AmsterdamUMC/AmsterdamUMCdb/blob/master/concepts/severityscores/sofa.ipynb)that the calculation accidentally uses the platelet value.  Its in input cell 36:

```
#calculate SOFA liver score:
sofa_bilirubin.loc[:,'sofa_liver_score'] = 0
sofa_bilirubin.loc[(sofa_bilirubin['value'] >= 20) & (sofa_bilirubin['value'] < 33), 'sofa_liver_score'] = 1
sofa_bilirubin.loc[(sofa_bilirubin['value'] >= 33) & (sofa_platelets['value'] < 102), 'sofa_liver_score'] = 2
sofa_bilirubin.loc[(sofa_bilirubin['value'] >= 102) & (sofa_platelets['value'] < 204), 'sofa_liver_score'] = 3
sofa_bilirubin.loc[(sofa_bilirubin['value'] >= 204), 'sofa_liver_score'] = 4

sofa_bilirubin.head()
```

you can see in lines 4 and 5 that it performs the logic with sofa_platelets not sofa_bilirubin

Hope this helps

**Comment by patrickthoral** [comment]
Good find! I labelled it as a bug, and will try to fix it asap.
