### ISSUE TITLE
ITEM dictionary required

### ISSUE THREAD

**Issue by peiyaoli** [AmsterdamUMC/AmsterdamUMCdb#4]
Hi, I would suggest to build a dictionary of items for numericitems like MIMIC does. In current settings, it takes a long time to search and locate correct labtest items.

**Comment by patrickthoral** [comment]
That's an excellent suggestion. Do you think we should add this as separate csv files (e.g. numerics) in the dataset or just create a view or table after the indexing?

**Comment by peiyaoli** [comment]
I think both ways are fine.  Maybe materialized view would be better.

**Comment by patrickthoral** [comment]
The `amsterdamumcdb` package now contains some utility functions used in the Notebooks, including with work-in-progress tranlations for commonly used items. The package can be installed from the Python Package Index respository (PiPy) by running:

> pip install amsterdamumcdb.

So I'm closing this issue.
