### ISSUE TITLE
encoding problem

### ISSUE THREAD

**Issue by SandyBy** [AmsterdamUMC/AmsterdamUMCdb#46]
sorry to bother. When I set up the database, the encoding problem struggled me. I had to change  SET CLIENT_ENCODING TO 'utf8' for the following 2 cells, otherwise error occured as below. When I set up the database,  I try to join two tables in one sql query which using two encoing , conflicts and error occurred again. I don't know how I could solve this. Could you help me,THX in advance!
![image](https://user-images.githubusercontent.com/46986985/120484245-76068d00-c3e5-11eb-916e-9a33990f3467.png)
![image](https://user-images.githubusercontent.com/46986985/120484341-8f0f3e00-c3e5-11eb-93ac-5c0fab8da183.png)
![image](https://user-images.githubusercontent.com/46986985/120484584-cc73cb80-c3e5-11eb-8efa-f1814f024386.png)

**Comment by patrickthoral** [comment]
Just to verify: did you clone the repository and are running the `setup-amsterdamumc.ipynb` notebook or did you copy and paste the cells to a new notebook? Are you using the latest release of the database (v.1.0.2?)

**Comment by SandyBy** [comment]
yes, I clone the repository and use v.1.0.2. I kind of doubt the files were broken while unzipping. I'll try again and see if it works and I'll let you know. Thanks for ur kind reply.

**Comment by SandyBy** [comment]
Yes. Create admissions table is the first cell that fails. I don't know why, but problem solved  by putting the following two together. Still confused. but It seems everything goes well so far.
SET CLIENT_ENCODING TO 'win1252'
SET CLIENT_ENCODING TO 'utf8'
![image](https://user-images.githubusercontent.com/46986985/122635509-f41da000-d116-11eb-8232-6d767e9d6ae6.png)

**Comment by patrickthoral** [comment]
Some of the documentation of postgres suggests that a non-standard codepage on the postgres server on Windows (i.e. not `WIN1252`) prevents the `WIN1252` codepage from working. I assume this is basically not related to AmsterdamUMCdb. I'm closing this now, but feel free to open.
