### ISSUE TITLE
confused numeric items

### ISSUE THREAD

**Issue by peiyaoli** [AmsterdamUMC/AmsterdamUMCdb#5]
Hi, I am working on query some of laboratory test items, but I am not sure whether some of those are the same things or not. This is because I am not familar with this database, on the other hand, some of context in the table are not in pure English which brings some trouble. I have to explore with guess with correlation and count number. Here are what I have found not not sure, could you please help me identify the correct items. If I miss something, please let me know.

laboratory test items | itemid | label in AUMC |count| similar items
---|---|---|---|---
albumin| 9937 | Alb.Chem (bloed)|104659|
creatinine| 9941| Kreatinine (bloed)|197746|Kreatinine
glucose | 9947| Glucose (bloed) | 825213|
platelet| 9964| Thrombo's (bloed) | 215873|
white blood count | 9965 | Leuco's (bloed) | 192600
bicarbonate | 9992 | Act.HCO3 | 660773
lactate | 10053 | Lactaat (bloed) | 182612
sodium | 9924 | Natrium (bloed) | 228315| Na (onv.ISE)   (bloed)
potassium | 9927 | Kalium (bloed)|222598|K (onv.ISE) (bloed)
hemoglobin|9960 | Hb (bloed) | 217560 | Hb (onv.ISE) (bloed)
Blood Urea Nitrogen| Not found

Many thanks!

**Comment by patrickthoral** [comment]
Hello @peiyaoli, you were quite on track by finding the associated Dutch names. *Blood urea nitrogen*  is ureum in Dutch. It's good to know that not all lab devices were interfaced with our PDMS right from the start so there are itemids with a lower number that correspond to manually entered labs (i.e. by nurses and physicians) and the higher numbers (> 9600) were automatically stored in the system. In addition, sometimes there were different ways to measure basically the same things (e.g. haemoglobin or sodium) by chemistry or hematology lab or using point-of-care technology (POCT) such as blood gas analysis machines, that received different itemids. Since I already did some work to calculate APACHE, SOFA and some other metrics for our soon to be submitted paper i'm copying a SQL script where I used some of these mappings:

```SQL
SELECT 
    CASE
        WHEN itemid IN (
            9947, --Glucose (bloed)
            6833, --Glucose Bloed 
            9557 --Glucose Astrup
        ) THEN 'Glucose'
        WHEN itemid IN (
            9941, --Kreatinine (bloed) µmol/l
            6836, --Kreatinine µmol/l (erroneously documented as µmol)
            14216 --KREAT enzym. (bloed) µmol/l
        ) THEN 'Creatinine'
        WHEN itemid IN (
            9943, --Ureum (bloed)
            6850 --Ureum
        ) THEN 'Blood Urea Nitrogen'
        WHEN itemid IN (
            9960, --Hb (bloed)
            6778, --Hemoglobine
            10286, --Hb(v.Bgs) (bloed)
            19703, --Hb poct (bloed)
            9553 --CtHB Astrup
        ) THEN 'Haemoglobin'
        WHEN itemid IN (
            11423, --Ht (bloed)
            11545, --Ht(v.Bgs) (bloed)
            6777 --Hematocriet
        ) THEN 'Haematocrit'
        WHEN itemid IN (
            9964, --Thrombo's (bloed)
            6797, --Thrombocyten
            10409, --Thrombo's citr. bloed (bloed)
            14252 --Thrombo CD61 (bloed)
        ) THEN 'Platelets'
        WHEN itemid IN (
            9965, --Leuco's (bloed) 10^9/l
            6779 --Leucocyten 10^9/l
        ) THEN 'White blood cell count'
        WHEN itemid IN (
            9924, --Natrium (bloed)
            6840, --Natrium
            9555, --Natrium Astrup
            10284 --Na (onv.ISE) (bloed)
        ) THEN 'Sodium'
        WHEN itemid IN (
            9927, --Kalium (bloed) mmol/l
            9556, --Kalium Astrup mmol/l
            6835, --Kalium mmol/l
            10285 --K (onv.ISE) (bloed) mmol/l
        ) THEN 'Potassium'
        WHEN itemid IN (
            9952, --Magnesium (bloed)
            6839 --Magnesium
        ) THEN 'Magnesium'
        WHEN itemid IN (
            10079, --CRP (bloed)
            6825 --CRP
        ) THEN 'C-reactive protein'
        WHEN itemid IN (
            9935, --Fosfaat (bloed)
            6828 --Fosfaat
        ) THEN 'Phosphate'
        WHEN itemid IN (
            11998, --CK (bloed)
            6822 --CK
        ) THEN 'Creatine kinase'
        WHEN itemid IN (
            9937, --Alb.Chem (bloed)
            6801 --Albumine chemisch
        ) THEN 'Serum albumin'
        WHEN itemid IN (
            11978, --ALAT (bloed)
            6800 --ALAT
        ) THEN 'ALAT'
        WHEN itemid IN (
            11990, --ASAT (bloed)
            6806 --ASAT
        ) THEN 'ASAT'
        WHEN itemid IN (
            10053, --Lactaat (bloed)
            6837, --Laktaat
            9580 --Laktaat Astrup
        ) THEN 'Lactate'
        WHEN itemid IN (
            12023, --LD (bloed)
            6838 --LDH
        ) THEN 'Lactate dehydrogenase'
        WHEN itemid IN (
            11984, --Alk.Fosf. (bloed)
            6803 --Alk. Fosfatase
        ) THEN 'Alkaline phosphatase'
        WHEN itemid IN (
            9945, --Bilirubine (bloed)
            6813 --Bili Totaal
        ) THEN 'Bilirubin'
        WHEN itemid IN (
            11925, --TSH (bloed)
            7071 --TSH
        ) THEN 'TSH'
        WHEN itemid IN (
            12310, --pH (bloed)
            6848 --PH
        ) THEN 'pH'
        WHEN itemid IN (
            6846, --PCO2
            9990, --pCO2 (bloed)
            21213 --PCO2 (bloed) - kPa
        ) THEN 'PCO2'
        WHEN itemid IN (
            7433, --PO2
            9996, --PO2 (bloed)
            21214 --PO2 (bloed) - kPa
        ) THEN 'PO2'
        WHEN itemid IN (
            9994, --B.E. (bloed)
            6807 --B.E.
        ) THEN 'Base Excess'
        WHEN itemid IN (
            9992, --Act.HCO3 (bloed)
            6810 --HCO3
        ) THEN 'Actual Bicarbonate'
        WHEN itemid IN (
            9559, --Anion-Gap (bloed)
            8492 --AnGap
        ) THEN 'Anion gap'        
        WHEN itemid IN (
            12311, --O2-Saturatie (bloed)
            8903 --SO2
        ) THEN 'O2 saturation'
    ELSE item
    END AS mapped_item,
    COUNT(DISTINCT admissionid) AS n_admissions_documented
FROM numericitems
WHERE islabresult = B'1'
GROUP BY mapped_item
ORDER BY COUNT(DISTINCT admissionid) DESC
```
Most of these grouped items have the same unit, with the notable exception of PO2 and PCO2 that are either in mmHg or kPa. And of course: we use the International System of Units (SI) in the Netherlands, so most units *will* differ from MIMIC or eICU.

Hope this helps.

Patrick

**Comment by peiyaoli** [comment]
@patrickthoral Hi, Patrick, thank you so much! This is same as what I guessed, data came from different collection scheme.
