### ISSUE TITLE
Laboratory vs blood gas sodium values

### ISSUE THREAD

**Issue by ariercole** [AmsterdamUMC/AmsterdamUMCdb#50]

**Comment by ariercole** [comment]
Can you clarify which numericitems table itemids / names contain lab and which contain blood gas sodiums measurements? It's not totally clear to me looking at the data and the numbers of readings seem small for the number of admissions? Thanks!

**Comment by patrickthoral** [comment]
```
import amsterdamumcdb as adb
dictionary = adb.get_dictionary()
dictionary[dictionary['item_en'].str.contains('sodium', case=False, regex=True) & (dictionary['islabresult'] == True)]
```


itemid | item | item_en | count
 -- | -- | -- | --
9555 | Natrium Astrup | sodium - direct ion specific electrode measur... | 19785
6840 | Natrium | serum sodium | 8602
9924 | Natrium (bloed) | sodium | 226219
10284 | Na (onv.ISE) (bloed) | sodium - direct ion specific electrode measure... | 527724

The ion specific electrode measurements are from the blood gas analyzer
