### ISSUE TITLE
language problem of the database!

### ISSUE THREAD

**Issue by pxjsmile** [AmsterdamUMC/AmsterdamUMCdb#52]
DANS only offered the version that is partly in Dutch and partly in English. If there is another version completely in English?
    Thank you very much!

**Comment by patrickthoral** [comment]
The database is from an actual Dutch hospital in which Dutch is the native language. So there is no 'completely English' version. However, you may have a look here for the dictionary: https://github.com/AmsterdamUMC/AmsterdamUMCdb#available-functions.
