### ISSUE TITLE
Preferred Citation

### ISSUE THREAD

**Issue by ajb5d** [AmsterdamUMC/AmsterdamUMCdb#7]
I see that there's a manuscript in the GitHub repository. Is there a preferred citation for this database?

**Comment by patrickthoral** [comment]
Preferred citation pending review and publication of submitted paper:
1. Thoral PJ, Peppink JM, Driessen RH, et al (2020) AmsterdamUMCdb: The First Freely Accessible European Intensive Care Database from the ESICM Data Sharing Initiative. access: https://www.amsterdammedicaldatascience.nl/; schemes: https://github.com/AmsterdamUMC/AmsterdamUMCdb; data: doi:10.17026/dans-22u-f8vd

**Comment by nbenn** [comment]
@patrickthoral Is there an update on this? Is a preprint version available somewhere?

**Comment by patrickthoral** [comment]
Yes, when using AmsterdamUMCdb in your research, please cite our Open Access manuscript:

Thoral, P. J., Peppink, J. M., Driessen, R. H., Sijbrands, E. J. G., Kompanje, E. J. O., Kaplan, L., Bailey, H., Kesecioglu, J., Cecconi, M., Churpek, M., Clermont, G., van der Schaar, M., Ercole, A., Girbes, A. R. J., Elbers, P. W. G., on behalf of the Amsterdam University Medical Centers Database (AmsterdamUMCdb) Collaborators and the SCCM/ESICM Joint Data Science Task Force (2021). Sharing ICU Patient Data Responsibly Under the Society of Critical Care Medicine/European Society of Intensive Care Medicine Joint Data Science Collaboration: The Amsterdam University Medical Centers Database (AmsterdamUMCdb) Example. Crit Care Med. 2021 Jun 1;49(6):e563-e577. doi: [10.1097/CCM.0000000000004916](https://doi.org/10.1097/CCM.0000000000004916). PMID: 33625129; PMCID: PMC8132908.
