### ISSUE TITLE
can't find the blood urea nitrogen values 

### ISSUE THREAD

**Issue by LILIHAN-001** [AmsterdamUMC/AmsterdamUMCdb#75]
I am querying the blood urea nitrogen (BUN) in the numericitems.csv table of the AUMCdb database, but I cannot find any itemid for this feature. Can you please tell me the itemid of blood urea nitrogen? I also used amsterdamumcdb.get_dictionary(), but I still could not find it.
Thanks!

**Comment by patrickthoral** [comment]
Blood urea nitrogen is 'Ureum' in Dutch: `itemid 9943` and `itemid 6580`
