### ISSUE TITLE
The role of Aspirin in clinical treatment in Netherlands

### ISSUE THREAD

**Issue by pmugambi** [AmsterdamUMC/AmsterdamUMCdb#79]
I noticed that aspirin, is labelled as an analgesic in the dataset. In our previous analysis we examined it for treatment of Myocardial Infarction, as an anti-platelet, but not specifically for pain. Should we change the approach in this dataset? That is, should we only assume that aspirin is given as an analgesic?

**Comment by patrickthoral** [comment]
In the Netherlands Aspirin is uncommonly used as an analgesic in clinical practice. Normal analgesic dose is >= 500 mg, so based on the `drugitems` table the following `itemids` can be safely regarded as anti-platelet therapy:
itemid | item
-- | -- 
12438 | Acetylsalicylzuur (Aspegic)
12798 | Acetylsalicylzuur
6908 | Carbasalaat Calcium
9019 | Carbasalaatcalcium (Ascal)

There only a small number of doses >= 500 (68 of 24430 records) and even those are most likely loading doses of anti-platelet therapy (e.g. after myocardial infaraction, etc).
