### ISSUE TITLE
Identifying cardiac surgery patients

### ISSUE THREAD

**Issue by perryla** [AmsterdamUMC/AmsterdamUMCdb#98]
Thank you for all you have done to make the AUMCdb open access.

A quick query if you don't mind - would it be possible to identify the subset of patients who were admitted post cardiac surgery? I cannot ascertain this for sure by looking at the admissions table documentation, although my suspicion is that it may not be possible.

Thank you.

Luke Perry

**Comment by narkode** [comment]
You can extract the cardiothoracic surgery patients with the amsterdamumcdb module:

    # Install amsterdamumcdb
    pip install amsterdamumcdb

    # Import amsterdamumcdb
    import amsterdamumcdb as adb

    # Identify cardiothoracic surgery patients    
    cardiothoracic_surgery_df = adb.get_cardiothoracic_surgery_patients(con)
